import argparse
import csv
import inspect
import logging
import math
import os
import shutil
from datetime import timedelta
from pathlib import Path

import accelerate
import torch
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from accelerate import Accelerator, InitProcessGroupKwargs
from accelerate.logging import get_logger
from accelerate.utils import ProjectConfiguration
from huggingface_hub import create_repo, upload_folder
from packaging import version
from PIL import Image
from torch.utils.data import DataLoader, Dataset, Subset
from torchvision.transforms import InterpolationMode, RandomCrop
from torchvision.utils import make_grid, save_image
from tqdm.auto import tqdm

import diffusers
from diffusers import DDPMScheduler, UNet2DModel
from diffusers.optimization import get_scheduler
from diffusers.training_utils import EMAModel
from diffusers.utils import check_min_version, is_accelerate_version, is_tensorboard_available, is_wandb_available
from diffusers.utils.import_utils import is_xformers_available


check_min_version("0.37.0.dev0")

logger = get_logger(__name__, log_level="INFO")


def parse_int_label(value, label_name):
    try:
        label = int(float(str(value).strip()))
    except ValueError as exc:
        raise ValueError(f"{label_name} must be an integer-like value, got {value!r}") from exc
    return label


def parse_expansion_label(value):
    expansion = parse_int_label(value, "expansion")
    if expansion not in (0, 1):
        raise ValueError(f"expansion must be 0 or 1 for combo embedding, got {expansion}")
    return expansion


def parse_aggregate_class(value):
    aggregate_class = parse_int_label(value, "aggregate_class")
    if aggregate_class not in (0, 1, 2):
        raise ValueError(f"aggregate_class must be 0, 1, or 2, got {aggregate_class}")
    return aggregate_class


def parse_combo_id(value):
    combo_id = parse_int_label(value, "combo_id")
    if combo_id not in range(6):
        raise ValueError(f"combo_id must be in [0, 5], got {combo_id}")
    return combo_id


class CrackMaskConditionDataset(Dataset):
    def __init__(
        self,
        image_dir,
        mask_dir,
        aggregate_mask_dir,
        metadata_csv,
        resolution,
        expansion_min,
        expansion_max,
        center_crop=False,
        random_flip=False,
        random_rotate90=False,
        target_dilate_kernel=1,
    ):
        self.image_dir = Path(image_dir)
        self.mask_dir = Path(mask_dir)
        self.aggregate_mask_dir = Path(aggregate_mask_dir)
        self.resolution = resolution
        self.center_crop = center_crop
        self.random_flip = random_flip
        self.random_rotate90 = random_rotate90
        if target_dilate_kernel < 1 or target_dilate_kernel % 2 == 0:
            raise ValueError(f"target_dilate_kernel must be a positive odd integer, got {target_dilate_kernel}")
        self.target_dilate_kernel = target_dilate_kernel
        self.expansion_min = expansion_min
        self.expansion_max = expansion_max

        if expansion_max <= expansion_min:
            raise ValueError("--expansion_max must be greater than --expansion_min.")

        self.records = []
        with open(metadata_csv, newline="") as csv_file:
            reader = csv.DictReader(csv_file)
            for row in reader:
                required_columns = {"filename", "expansion", "aggregate_class", "combo_id"}
                missing_columns = required_columns - set(reader.fieldnames or [])
                if missing_columns:
                    raise ValueError(
                        "metadata.csv must be generated by write_exp_agg_labels_csv.py and contain "
                        f"columns: {', '.join(sorted(required_columns))}. "
                        f"Missing: {', '.join(sorted(missing_columns))}"
                    )

                filename = row["filename"].strip()
                expansion = parse_expansion_label(row["expansion"])
                aggregate_class = parse_aggregate_class(row["aggregate_class"])
                combo_id = parse_combo_id(row["combo_id"])
                expected_combo_id = aggregate_class * 2 + expansion
                if combo_id != expected_combo_id:
                    raise ValueError(
                        f"Invalid combo_id for {filename}: got {combo_id}, expected "
                        f"aggregate_class * 2 + expansion = {expected_combo_id}"
                    )
                self.records.append(
                    {
                        "filename": filename,
                        "expansion": expansion,
                        "aggregate_class": aggregate_class,
                        "combo_id": combo_id,
                    }
                )

        if len(self.records) == 0:
            raise ValueError("No samples were found in metadata.csv.")

    def __len__(self):
        return len(self.records)

    def _paired_spatial_transform(self, image, mask, aggregate_mask):
        image = TF.resize(image, self.resolution, interpolation=InterpolationMode.BILINEAR)
        mask = TF.resize(mask, self.resolution, interpolation=InterpolationMode.NEAREST)
        aggregate_mask = TF.resize(aggregate_mask, self.resolution, interpolation=InterpolationMode.NEAREST)

        if self.center_crop:
            image = TF.center_crop(image, [self.resolution, self.resolution])
            mask = TF.center_crop(mask, [self.resolution, self.resolution])
            aggregate_mask = TF.center_crop(aggregate_mask, [self.resolution, self.resolution])
        else:
            top, left, height, width = RandomCrop.get_params(image, output_size=(self.resolution, self.resolution))
            image = TF.crop(image, top, left, height, width)
            mask = TF.crop(mask, top, left, height, width)
            aggregate_mask = TF.crop(aggregate_mask, top, left, height, width)

        if self.random_flip and torch.rand(1).item() < 0.5:
            image = TF.hflip(image)
            mask = TF.hflip(mask)
            aggregate_mask = TF.hflip(aggregate_mask)

        if self.random_rotate90:
            k = int(torch.randint(0, 4, (1,)).item())
            if k != 0:
                angle = 90.0 * k
                image = TF.rotate(image, angle, interpolation=InterpolationMode.BILINEAR)
                mask = TF.rotate(mask, angle, interpolation=InterpolationMode.NEAREST)
                aggregate_mask = TF.rotate(aggregate_mask, angle, interpolation=InterpolationMode.NEAREST)

        return image, mask, aggregate_mask

    def __getitem__(self, index):
        record = self.records[index]
        image_path = self.image_dir / record["filename"]
        mask_path = self.mask_dir / record["filename"]
        aggregate_mask_path = self.aggregate_mask_dir / record["filename"]

        if not image_path.exists():
            raise FileNotFoundError(f"Missing image file: {image_path}")
        if not mask_path.exists():
            raise FileNotFoundError(f"Missing mask file: {mask_path}")
        if not aggregate_mask_path.exists():
            raise FileNotFoundError(f"Missing aggregate mask file: {aggregate_mask_path}")

        image = Image.open(image_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")
        aggregate_mask = Image.open(aggregate_mask_path).convert("L")
        image, mask, aggregate_mask = self._paired_spatial_transform(image, mask, aggregate_mask)

        image = TF.to_tensor(image)
        image = image * 2.0 - 1.0

        # Continuous antialiased mask in [0, 1]; no binary thresholding so edge gradients survive.
        mask = TF.to_tensor(mask)
        # Dilate the GT crack so a 1-2px line survives the UNet bottleneck. Inference can erode/skeletonize back.
        if self.target_dilate_kernel >= 3:
            pad = self.target_dilate_kernel // 2
            mask = F.max_pool2d(
                mask.unsqueeze(0), kernel_size=self.target_dilate_kernel, stride=1, padding=pad
            ).squeeze(0)
        mask = mask * 2.0 - 1.0

        # Aggregate mask is already binary in source; keep it binary in [-1, 1].
        aggregate_mask = TF.to_tensor(aggregate_mask)
        aggregate_mask = (aggregate_mask > 0.5).float()
        aggregate_mask = aggregate_mask * 2.0 - 1.0

        return {
            "image": image,
            "mask": mask,
            "aggregate_mask": aggregate_mask,
            "filename": record["filename"],
            "expansion": torch.tensor(record["expansion"], dtype=torch.long),
            "aggregate_class": torch.tensor(record["aggregate_class"], dtype=torch.long),
            "combo_id": torch.tensor(record["combo_id"], dtype=torch.long),
        }


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Conditional crack-mask DDPM training: x0 (sample) prediction, GT-mask dilation, "
            "clDice-leading loss mix, and aggregate-channel dropout to break copy-paste leak."
        )
    )
    parser.add_argument("--image_dir", type=str, required=True)
    parser.add_argument("--mask_dir", type=str, required=True)
    parser.add_argument("--aggregate_mask_dir", type=str, required=True)
    parser.add_argument("--metadata_csv", type=str, required=True)
    parser.add_argument("--expansion_min", type=float, required=True)
    parser.add_argument("--expansion_max", type=float, required=True)
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument(
        "--diffusion_loss_weight",
        type=float,
        default=1.0,
        help="Weight on the MSE between predicted x0 and clean mask (the diffusion training loss for sample-prediction).",
    )
    parser.add_argument("--bce_weight", type=float, default=0.2, help="Plain (unweighted) BCE on probabilities.")
    parser.add_argument("--dice_weight", type=float, default=0.3)
    parser.add_argument("--cldice_weight", type=float, default=0.5, help="Soft clDice loss on probabilities.")
    parser.add_argument("--soft_cldice_iterations", type=int, default=10)
    parser.add_argument(
        "--aggregate_penalty_weight",
        type=float,
        default=0.05,
        help="Soft penalty on predicted-mask probability falling outside a dilated aggregate-mask support.",
    )
    parser.add_argument(
        "--aggregate_dilate_kernel",
        type=int,
        default=15,
        help="Odd kernel size used to dilate the aggregate mask before applying the localization penalty.",
    )
    parser.add_argument(
        "--reconstruction_max_timestep",
        type=int,
        default=-1,
        help="If >= 0, only apply auxiliary (BCE/Dice/clDice/aggregate) losses to t <= this value. -1 = all timesteps.",
    )
    parser.add_argument(
        "--cfg_drop_prob",
        type=float,
        default=0.1,
        help="Probability of replacing the combo_id with the null class id during training (classifier-free guidance).",
    )
    parser.add_argument(
        "--aggregate_channel_dropout",
        type=float,
        default=0.0,
        help=(
            "Per-sample probability of zeroing the aggregate-mask conditioning channel during training. "
            "Forces the model to use the channel as a soft cue rather than a copy-paste template. 0 = always pass."
        ),
    )
    parser.add_argument("--null_class_id", type=int, default=6)
    parser.add_argument("--num_class_embeds", type=int, default=7)
    parser.add_argument(
        "--validation_guidance_scale",
        type=float,
        default=0.0,
        help="If > 0, run classifier-free guidance during validation sampling with this scale.",
    )
    parser.add_argument("--validation_seed", type=int, default=0)
    parser.add_argument("--model_config_name_or_path", type=str, default=None)
    parser.add_argument("--output_dir", type=str, default="conditional-crack-mask-ddpm")
    parser.add_argument("--overwrite_output_dir", action="store_true")
    parser.add_argument("--cache_dir", type=str, default=None)
    parser.add_argument("--resolution", type=int, default=64)
    parser.add_argument("--center_crop", default=False, action="store_true")
    parser.add_argument("--random_flip", default=False, action="store_true")
    parser.add_argument("--random_rotate90", default=False, action="store_true")
    parser.add_argument(
        "--target_dilate_kernel",
        type=int,
        default=1,
        help="Odd kernel size used to dilate the GT crack mask before noising. 1 = no dilation. Recommended 3-7 at low resolution to keep thin cracks representable through the UNet bottleneck.",
    )
    parser.add_argument("--train_batch_size", type=int, default=16)
    parser.add_argument("--eval_batch_size", type=int, default=16)
    parser.add_argument("--dataloader_num_workers", type=int, default=0)
    parser.add_argument("--num_epochs", type=int, default=100)
    parser.add_argument("--save_images_epochs", type=int, default=10)
    parser.add_argument("--save_model_epochs", type=int, default=10)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--lr_scheduler", type=str, default="cosine")
    parser.add_argument("--lr_warmup_steps", type=int, default=500)
    parser.add_argument("--adam_beta1", type=float, default=0.95)
    parser.add_argument("--adam_beta2", type=float, default=0.999)
    parser.add_argument("--adam_weight_decay", type=float, default=1e-6)
    parser.add_argument("--adam_epsilon", type=float, default=1e-08)
    parser.add_argument("--use_ema", action="store_true")
    parser.add_argument("--ema_inv_gamma", type=float, default=1.0)
    parser.add_argument("--ema_power", type=float, default=3 / 4)
    parser.add_argument("--ema_max_decay", type=float, default=0.9999)
    parser.add_argument("--push_to_hub", action="store_true")
    parser.add_argument("--hub_token", type=str, default=None)
    parser.add_argument("--hub_model_id", type=str, default=None)
    parser.add_argument("--hub_private_repo", action="store_true")
    parser.add_argument("--logger", type=str, default="tensorboard", choices=["tensorboard", "wandb"])
    parser.add_argument("--logging_dir", type=str, default="logs")
    parser.add_argument("--local_rank", type=int, default=-1)
    parser.add_argument("--mixed_precision", type=str, default="no", choices=["no", "fp16", "bf16"])
    parser.add_argument(
        "--prediction_type",
        type=str,
        default="sample",
        choices=["sample"],
        help="This script targets sample (x0) prediction; auxiliary losses act directly on the model output.",
    )
    parser.add_argument("--ddpm_num_steps", type=int, default=1000)
    parser.add_argument("--ddpm_num_inference_steps", type=int, default=1000)
    parser.add_argument("--ddpm_beta_schedule", type=str, default="linear")
    parser.add_argument("--checkpointing_steps", type=int, default=500)
    parser.add_argument("--checkpoints_total_limit", type=int, default=None)
    parser.add_argument("--resume_from_checkpoint", type=str, default=None)
    parser.add_argument("--enable_xformers_memory_efficient_attention", action="store_true")

    args = parser.parse_args()
    env_local_rank = int(os.environ.get("LOCAL_RANK", -1))
    if env_local_rank != -1 and env_local_rank != args.local_rank:
        args.local_rank = env_local_rank

    if args.null_class_id >= args.num_class_embeds:
        raise ValueError(
            f"--null_class_id ({args.null_class_id}) must be < --num_class_embeds ({args.num_class_embeds})."
        )

    if args.aggregate_dilate_kernel % 2 == 0:
        raise ValueError(f"--aggregate_dilate_kernel must be odd, got {args.aggregate_dilate_kernel}")

    return args


def collate_fn(examples):
    return {
        "image": torch.stack([example["image"] for example in examples]),
        "mask": torch.stack([example["mask"] for example in examples]),
        "aggregate_mask": torch.stack([example["aggregate_mask"] for example in examples]),
        "filename": [example["filename"] for example in examples],
        "expansion": torch.stack([example["expansion"] for example in examples]),
        "aggregate_class": torch.stack([example["aggregate_class"] for example in examples]),
        "combo_id": torch.stack([example["combo_id"] for example in examples]),
    }


def prepare_validation_batch(validation_dataset, eval_batch_size):
    if len(validation_dataset) == 0:
        return None
    subset = Subset(validation_dataset, range(min(eval_batch_size, len(validation_dataset))))
    validation_loader = DataLoader(subset, batch_size=len(subset), shuffle=False, collate_fn=collate_fn)
    return next(iter(validation_loader))


def build_validation_grid(concrete_images, aggregate_masks, gt_masks, pred_masks, binary_masks):
    rows = []
    for concrete_image, aggregate_mask, gt_mask, pred_mask, binary_mask in zip(
        concrete_images, aggregate_masks, gt_masks, pred_masks, binary_masks
    ):
        concrete_image = (concrete_image.clamp(-1, 1) + 1.0) / 2.0
        aggregate_mask = aggregate_mask.repeat(3, 1, 1)
        gt_mask_rgb = gt_mask.repeat(3, 1, 1)
        pred_mask_rgb = pred_mask.repeat(3, 1, 1)
        binary_mask_rgb = binary_mask.repeat(3, 1, 1)
        rows.append(torch.cat([concrete_image, aggregate_mask, gt_mask_rgb, pred_mask_rgb, binary_mask_rgb], dim=2))
    return make_grid(rows, nrow=1)


def dice_loss(pred_mask_prob, target_mask_prob, eps=1e-6):
    pred = pred_mask_prob.reshape(pred_mask_prob.shape[0], -1)
    target = target_mask_prob.reshape(target_mask_prob.shape[0], -1)
    intersection = (pred * target).sum(dim=1)
    denominator = pred.sum(dim=1) + target.sum(dim=1)
    dice = (2.0 * intersection + eps) / (denominator + eps)
    return 1.0 - dice.mean()


def soft_erode(mask_prob):
    eroded_h = -F.max_pool2d(-mask_prob, kernel_size=(3, 1), stride=1, padding=(1, 0))
    eroded_w = -F.max_pool2d(-mask_prob, kernel_size=(1, 3), stride=1, padding=(0, 1))
    return torch.minimum(eroded_h, eroded_w)


def soft_dilate(mask_prob):
    return F.max_pool2d(mask_prob, kernel_size=3, stride=1, padding=1)


def soft_dilate_k(mask_prob, kernel_size):
    pad = kernel_size // 2
    return F.max_pool2d(mask_prob, kernel_size=kernel_size, stride=1, padding=pad)


def soft_open(mask_prob):
    return soft_dilate(soft_erode(mask_prob))


def soft_skeletonize(mask_prob, iterations):
    opened = soft_open(mask_prob)
    skeleton = F.relu(mask_prob - opened)
    for _ in range(iterations):
        mask_prob = soft_erode(mask_prob)
        opened = soft_open(mask_prob)
        delta = F.relu(mask_prob - opened)
        skeleton = skeleton + F.relu(delta - skeleton * delta)
    return skeleton


def soft_cldice_loss(pred_mask_prob, target_mask_prob, iterations=10, eps=1e-6):
    pred_skeleton = soft_skeletonize(pred_mask_prob, iterations)
    target_skeleton = soft_skeletonize(target_mask_prob, iterations)

    pred = pred_mask_prob.reshape(pred_mask_prob.shape[0], -1)
    target = target_mask_prob.reshape(target_mask_prob.shape[0], -1)
    pred_skel = pred_skeleton.reshape(pred_skeleton.shape[0], -1)
    target_skel = target_skeleton.reshape(target_skeleton.shape[0], -1)

    topology_precision = (pred_skel * target).sum(dim=1) / (pred_skel.sum(dim=1) + eps)
    topology_sensitivity = (target_skel * pred).sum(dim=1) / (target_skel.sum(dim=1) + eps)
    cldice = (2.0 * topology_precision * topology_sensitivity + eps) / (
        topology_precision + topology_sensitivity + eps
    )
    return 1.0 - cldice.mean()


def masks_to_probability(pred_x0, clean_mask):
    pred_prob = ((pred_x0.clamp(-1, 1) + 1.0) / 2.0).float()
    target_prob = ((clean_mask.clamp(-1, 1) + 1.0) / 2.0).float()
    return pred_prob, target_prob


def aggregate_localization_penalty(pred_prob, agg_prob, dilate_kernel):
    if dilate_kernel >= 3:
        agg_dilated = soft_dilate_k(agg_prob, dilate_kernel)
    else:
        agg_dilated = agg_prob
    out_of_support = (1.0 - agg_dilated).clamp(0.0, 1.0)
    return (pred_prob * out_of_support).mean()


@torch.no_grad()
def run_validation(unet, noise_scheduler, validation_batch, epoch, args, accelerator, weight_dtype):
    if validation_batch is None:
        return

    unet.eval()

    concrete_image = validation_batch["image"].to(device=accelerator.device, dtype=weight_dtype)
    gt_mask = validation_batch["mask"].to(device=accelerator.device, dtype=weight_dtype)
    aggregate_mask = validation_batch["aggregate_mask"].to(device=accelerator.device, dtype=weight_dtype)
    combo_id = validation_batch["combo_id"].to(device=accelerator.device, dtype=torch.long)
    null_id = torch.full_like(combo_id, args.null_class_id)

    validation_generator = torch.Generator(device=accelerator.device)
    validation_generator.manual_seed(args.validation_seed)
    mask = torch.randn(
        (concrete_image.shape[0], 1, args.resolution, args.resolution),
        device=accelerator.device,
        dtype=weight_dtype,
        generator=validation_generator,
    )

    cfg_scale = args.validation_guidance_scale
    use_cfg = cfg_scale > 0.0

    noise_scheduler.set_timesteps(args.ddpm_num_inference_steps)
    for t in noise_scheduler.timesteps:
        timestep_batch = torch.full((mask.shape[0],), int(t), device=mask.device, dtype=torch.long)
        model_input = torch.cat([mask, concrete_image, aggregate_mask], dim=1)
        if use_cfg:
            pred_cond = unet(model_input, timestep_batch, class_labels=combo_id).sample
            pred_uncond = unet(model_input, timestep_batch, class_labels=null_id).sample
            model_pred = pred_uncond + cfg_scale * (pred_cond - pred_uncond)
        else:
            model_pred = unet(model_input, timestep_batch, class_labels=combo_id).sample
        mask = noise_scheduler.step(model_pred, t, mask).prev_sample

    pred_mask = ((mask.clamp(-1, 1) + 1.0) / 2.0).float().cpu()
    gt_mask = ((gt_mask.clamp(-1, 1) + 1.0) / 2.0).float().cpu()
    aggregate_mask = ((aggregate_mask.clamp(-1, 1) + 1.0) / 2.0).float().cpu()
    concrete_image = concrete_image.float().cpu()
    binary_mask = (pred_mask > args.threshold).float()

    grid = build_validation_grid(concrete_image, aggregate_mask, gt_mask, pred_mask, binary_mask)

    sample_dir = os.path.join(args.output_dir, "samples")
    os.makedirs(sample_dir, exist_ok=True)
    sample_path = os.path.join(sample_dir, f"epoch_{epoch:04d}.png")
    save_image(grid, sample_path)

    if args.logger == "tensorboard":
        if is_accelerate_version(">=", "0.17.0.dev0"):
            tracker = accelerator.get_tracker("tensorboard", unwrap=True)
        else:
            tracker = accelerator.get_tracker("tensorboard")
        tracker.add_image("validation_samples", grid, epoch)
    elif args.logger == "wandb":
        import wandb

        accelerator.get_tracker("wandb").log(
            {
                "validation_samples": wandb.Image(
                    sample_path,
                    caption="Columns: concrete image | aggregate mask | gt mask | generated mask | thresholded mask",
                ),
                "epoch": epoch,
            },
            step=epoch,
        )

    unet.train()


def save_conditional_components(unet, noise_scheduler, output_dir):
    unet.save_pretrained(os.path.join(output_dir, "unet"))
    noise_scheduler.save_pretrained(os.path.join(output_dir, "scheduler"))


def main(args):
    logging_dir = os.path.join(args.output_dir, args.logging_dir)
    accelerator_project_config = ProjectConfiguration(project_dir=args.output_dir, logging_dir=logging_dir)

    kwargs = InitProcessGroupKwargs(timeout=timedelta(seconds=7200))
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.logger,
        project_config=accelerator_project_config,
        kwargs_handlers=[kwargs],
    )

    if args.logger == "tensorboard":
        if not is_tensorboard_available():
            raise ImportError("Make sure to install tensorboard if you want to use it for logging during training.")
    elif args.logger == "wandb":
        if not is_wandb_available():
            raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
        import wandb

    if version.parse(accelerate.__version__) >= version.parse("0.16.0"):

        def save_model_hook(models, weights, output_dir):
            if accelerator.is_main_process:
                if args.use_ema:
                    ema_model.save_pretrained(os.path.join(output_dir, "unet_ema"))

                for _model in models:
                    _model.save_pretrained(os.path.join(output_dir, "unet"))
                    weights.pop()

                noise_scheduler.save_pretrained(os.path.join(output_dir, "scheduler"))

        def load_model_hook(models, input_dir):
            if args.use_ema:
                load_model = EMAModel.from_pretrained(os.path.join(input_dir, "unet_ema"), UNet2DModel)
                ema_model.load_state_dict(load_model.state_dict())
                ema_model.to(accelerator.device)
                del load_model

            for _ in range(len(models)):
                model = models.pop()
                load_model = UNet2DModel.from_pretrained(input_dir, subfolder="unet")
                model.register_to_config(**load_model.config)
                model.load_state_dict(load_model.state_dict())
                del load_model

            scheduler_dir = os.path.join(input_dir, "scheduler")
            if os.path.isdir(scheduler_dir):
                loaded_scheduler = DDPMScheduler.from_pretrained(input_dir, subfolder="scheduler")
                noise_scheduler.register_to_config(**loaded_scheduler.config)

        accelerator.register_save_state_pre_hook(save_model_hook)
        accelerator.register_load_state_pre_hook(load_model_hook)

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logger.info(accelerator.state, main_process_only=False)
    if accelerator.is_local_main_process:
        diffusers.utils.logging.set_verbosity_info()
    else:
        diffusers.utils.logging.set_verbosity_error()

    if accelerator.is_main_process:
        if args.output_dir is not None:
            os.makedirs(args.output_dir, exist_ok=True)

        if args.push_to_hub:
            repo_id = create_repo(
                repo_id=args.hub_model_id or Path(args.output_dir).name,
                exist_ok=True,
                token=args.hub_token,
                private=args.hub_private_repo,
            ).repo_id

    if args.model_config_name_or_path is None:
        model = UNet2DModel(
            sample_size=args.resolution,
            in_channels=5,
            out_channels=1,
            num_class_embeds=args.num_class_embeds,
            layers_per_block=2,
            block_out_channels=(128, 128, 256, 256, 512, 512),
            down_block_types=(
                "DownBlock2D",
                "DownBlock2D",
                "DownBlock2D",
                "DownBlock2D",
                "AttnDownBlock2D",
                "DownBlock2D",
            ),
            up_block_types=(
                "UpBlock2D",
                "AttnUpBlock2D",
                "UpBlock2D",
                "UpBlock2D",
                "UpBlock2D",
                "UpBlock2D",
            ),
        )
    else:
        config = dict(UNet2DModel.load_config(args.model_config_name_or_path))
        config.update(
            {
                "sample_size": args.resolution,
                "in_channels": 5,
                "out_channels": 1,
                "num_class_embeds": args.num_class_embeds,
            }
        )
        model = UNet2DModel.from_config(config)

    if args.use_ema:
        ema_model = EMAModel(
            model.parameters(),
            decay=args.ema_max_decay,
            use_ema_warmup=True,
            inv_gamma=args.ema_inv_gamma,
            power=args.ema_power,
            model_cls=UNet2DModel,
            model_config=model.config,
        )

    weight_dtype = torch.float32
    if accelerator.mixed_precision == "fp16":
        weight_dtype = torch.float16
        args.mixed_precision = accelerator.mixed_precision
    elif accelerator.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16
        args.mixed_precision = accelerator.mixed_precision

    if args.enable_xformers_memory_efficient_attention:
        if is_xformers_available():
            import xformers

            xformers_version = version.parse(xformers.__version__)
            if xformers_version == version.parse("0.0.16"):
                logger.warning(
                    "xFormers 0.0.16 cannot be used for training in some GPUs. If you observe problems during "
                    "training, please update xFormers to at least 0.0.17."
                )
            model.enable_xformers_memory_efficient_attention()
        else:
            raise ValueError("xformers is not available. Make sure it is installed correctly")

    accepts_prediction_type = "prediction_type" in set(inspect.signature(DDPMScheduler.__init__).parameters.keys())
    if accepts_prediction_type:
        noise_scheduler = DDPMScheduler(
            num_train_timesteps=args.ddpm_num_steps,
            beta_schedule=args.ddpm_beta_schedule,
            prediction_type=args.prediction_type,
        )
    else:
        raise RuntimeError(
            "Installed diffusers DDPMScheduler does not accept prediction_type; this script requires sample-prediction support."
        )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        betas=(args.adam_beta1, args.adam_beta2),
        weight_decay=args.adam_weight_decay,
        eps=args.adam_epsilon,
    )

    train_dataset = CrackMaskConditionDataset(
        image_dir=args.image_dir,
        mask_dir=args.mask_dir,
        aggregate_mask_dir=args.aggregate_mask_dir,
        metadata_csv=args.metadata_csv,
        resolution=args.resolution,
        expansion_min=args.expansion_min,
        expansion_max=args.expansion_max,
        center_crop=args.center_crop,
        random_flip=args.random_flip,
        random_rotate90=args.random_rotate90,
        target_dilate_kernel=args.target_dilate_kernel,
    )
    validation_dataset = CrackMaskConditionDataset(
        image_dir=args.image_dir,
        mask_dir=args.mask_dir,
        aggregate_mask_dir=args.aggregate_mask_dir,
        metadata_csv=args.metadata_csv,
        resolution=args.resolution,
        expansion_min=args.expansion_min,
        expansion_max=args.expansion_max,
        center_crop=True,
        random_flip=False,
        random_rotate90=False,
        target_dilate_kernel=args.target_dilate_kernel,
    )

    logger.info(f"Dataset size: {len(train_dataset)}")
    validation_batch = prepare_validation_batch(validation_dataset, args.eval_batch_size)

    train_dataloader = DataLoader(
        train_dataset,
        batch_size=args.train_batch_size,
        shuffle=True,
        num_workers=args.dataloader_num_workers,
        collate_fn=collate_fn,
    )

    lr_scheduler = get_scheduler(
        args.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps * args.gradient_accumulation_steps,
        num_training_steps=(len(train_dataloader) * args.num_epochs),
    )

    model, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        model, optimizer, train_dataloader, lr_scheduler
    )

    if args.use_ema:
        ema_model.to(accelerator.device)

    if accelerator.is_main_process:
        run = os.path.split(__file__)[-1].split(".")[0]
        accelerator.init_trackers(run, config=vars(args))

    total_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps
    num_update_steps_per_epoch = math.ceil(len(train_dataloader) / args.gradient_accumulation_steps)
    max_train_steps = args.num_epochs * num_update_steps_per_epoch

    logger.info("***** Running training (x0/sample-prediction + dilated GT + BCE/Dice-primary) *****")
    logger.info(f"  Num examples = {len(train_dataset)}")
    logger.info(f"  Num Epochs = {args.num_epochs}")
    logger.info(f"  Instantaneous batch size per device = {args.train_batch_size}")
    logger.info(f"  Total train batch size (w. parallel, distributed & accumulation) = {total_batch_size}")
    logger.info(f"  Gradient Accumulation steps = {args.gradient_accumulation_steps}")
    logger.info(f"  Total optimization steps = {max_train_steps}")

    global_step = 0
    first_epoch = 0
    resume_step = 0

    if args.resume_from_checkpoint:
        if args.resume_from_checkpoint != "latest":
            path = os.path.basename(args.resume_from_checkpoint)
        else:
            dirs = os.listdir(args.output_dir)
            dirs = [d for d in dirs if d.startswith("checkpoint")]
            dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
            path = dirs[-1] if len(dirs) > 0 else None

        if path is None:
            accelerator.print(
                f"Checkpoint '{args.resume_from_checkpoint}' does not exist. Starting a new training run."
            )
            args.resume_from_checkpoint = None
        else:
            accelerator.print(f"Resuming from checkpoint {path}")
            accelerator.load_state(os.path.join(args.output_dir, path))
            global_step = int(path.split("-")[1])

            resume_global_step = global_step * args.gradient_accumulation_steps
            first_epoch = global_step // num_update_steps_per_epoch
            resume_step = resume_global_step % (num_update_steps_per_epoch * args.gradient_accumulation_steps)

    for epoch in range(first_epoch, args.num_epochs):
        model.train()
        progress_bar = tqdm(total=num_update_steps_per_epoch, disable=not accelerator.is_local_main_process)
        progress_bar.set_description(f"Epoch {epoch}")
        for step, batch in enumerate(train_dataloader):
            if args.resume_from_checkpoint and epoch == first_epoch and step < resume_step:
                if step % args.gradient_accumulation_steps == 0:
                    progress_bar.update(1)
                continue

            clean_mask = batch["mask"].to(dtype=weight_dtype)
            concrete_image = batch["image"].to(dtype=weight_dtype)
            aggregate_mask = batch["aggregate_mask"].to(dtype=weight_dtype)
            combo_id = batch["combo_id"].to(device=clean_mask.device, dtype=torch.long)

            if args.cfg_drop_prob > 0.0:
                drop = torch.rand(combo_id.shape, device=combo_id.device) < args.cfg_drop_prob
                combo_id = torch.where(drop, torch.full_like(combo_id, args.null_class_id), combo_id)

            if args.aggregate_channel_dropout > 0.0:
                # Per-sample dropout: with prob p, zero the aggregate-mask channel so the model can't
                # treat it as a copy-paste template for predictions.
                agg_drop = torch.rand(aggregate_mask.shape[0], device=aggregate_mask.device) < args.aggregate_channel_dropout
                keep_mask = (~agg_drop).to(dtype=aggregate_mask.dtype).view(-1, 1, 1, 1)
                aggregate_mask = aggregate_mask * keep_mask

            noise = torch.randn_like(clean_mask)
            bsz = clean_mask.shape[0]
            timesteps = torch.randint(
                0, noise_scheduler.config.num_train_timesteps, (bsz,), device=clean_mask.device
            ).long()

            noisy_mask = noise_scheduler.add_noise(clean_mask, noise, timesteps)
            model_input = torch.cat([noisy_mask, concrete_image, aggregate_mask], dim=1)

            with accelerator.accumulate(model):
                # With prediction_type="sample" the model output IS the predicted x0 in the same range as clean_mask.
                pred_x0 = model(model_input, timesteps, class_labels=combo_id).sample

                diffusion_loss = F.mse_loss(pred_x0.float(), clean_mask.float())

                bce_term = torch.zeros((), device=clean_mask.device, dtype=torch.float32)
                dice_term = torch.zeros((), device=clean_mask.device, dtype=torch.float32)
                cldice_term = torch.zeros((), device=clean_mask.device, dtype=torch.float32)
                agg_term = torch.zeros((), device=clean_mask.device, dtype=torch.float32)
                aux_fraction = torch.zeros((), device=clean_mask.device, dtype=torch.float32)

                aux_active = (
                    args.bce_weight > 0
                    or args.dice_weight > 0
                    or args.cldice_weight > 0
                    or args.aggregate_penalty_weight > 0
                )

                if aux_active:
                    if args.reconstruction_max_timestep >= 0:
                        keep = timesteps <= args.reconstruction_max_timestep
                    else:
                        keep = torch.ones_like(timesteps, dtype=torch.bool)

                    aux_fraction = keep.float().mean()

                    if keep.any():
                        sel_pred = pred_x0[keep]
                        sel_target = clean_mask[keep]
                        sel_agg = aggregate_mask[keep]

                        pred_prob, target_prob = masks_to_probability(sel_pred, sel_target)

                        if args.bce_weight > 0:
                            bce_term = F.binary_cross_entropy(
                                pred_prob.clamp(1e-6, 1.0 - 1e-6), target_prob
                            )
                        if args.dice_weight > 0:
                            dice_term = dice_loss(pred_prob, target_prob)
                        if args.cldice_weight > 0:
                            cldice_term = soft_cldice_loss(
                                pred_prob, target_prob, iterations=args.soft_cldice_iterations
                            )
                        if args.aggregate_penalty_weight > 0:
                            agg_prob = ((sel_agg.clamp(-1, 1) + 1.0) / 2.0).float()
                            agg_term = aggregate_localization_penalty(
                                pred_prob, agg_prob, args.aggregate_dilate_kernel
                            )

                loss = (
                    args.diffusion_loss_weight * diffusion_loss
                    + args.bce_weight * bce_term
                    + args.dice_weight * dice_term
                    + args.cldice_weight * cldice_term
                    + args.aggregate_penalty_weight * agg_term
                )

                accelerator.backward(loss)

                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

            if accelerator.sync_gradients:
                if args.use_ema:
                    ema_model.step(model.parameters())
                progress_bar.update(1)
                global_step += 1

                if accelerator.is_main_process:
                    if global_step % args.checkpointing_steps == 0:
                        if args.checkpoints_total_limit is not None:
                            checkpoints = os.listdir(args.output_dir)
                            checkpoints = [d for d in checkpoints if d.startswith("checkpoint")]
                            checkpoints = sorted(checkpoints, key=lambda x: int(x.split("-")[1]))

                            if len(checkpoints) >= args.checkpoints_total_limit:
                                num_to_remove = len(checkpoints) - args.checkpoints_total_limit + 1
                                removing_checkpoints = checkpoints[0:num_to_remove]

                                logger.info(
                                    f"{len(checkpoints)} checkpoints already exist, removing "
                                    f"{len(removing_checkpoints)} checkpoints"
                                )
                                logger.info(f"removing checkpoints: {', '.join(removing_checkpoints)}")

                                for removing_checkpoint in removing_checkpoints:
                                    removing_checkpoint = os.path.join(args.output_dir, removing_checkpoint)
                                    shutil.rmtree(removing_checkpoint)

                        save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")
                        accelerator.save_state(save_path)
                        logger.info(f"Saved state to {save_path}")

            logs = {
                "loss": loss.detach().item(),
                "diffusion_loss": diffusion_loss.detach().item(),
                "bce_loss": bce_term.detach().item(),
                "dice_loss": dice_term.detach().item(),
                "cldice_loss": cldice_term.detach().item(),
                "aggregate_penalty": agg_term.detach().item(),
                "aux_fraction": aux_fraction.detach().item(),
                "lr": lr_scheduler.get_last_lr()[0],
                "step": global_step,
            }
            if args.use_ema:
                logs["ema_decay"] = ema_model.cur_decay_value
            progress_bar.set_postfix(**logs)
            accelerator.log(logs, step=global_step)
        progress_bar.close()

        accelerator.wait_for_everyone()

        if accelerator.is_main_process:
            if epoch % args.save_images_epochs == 0 or epoch == args.num_epochs - 1:
                unet = accelerator.unwrap_model(model)

                if args.use_ema:
                    ema_model.store(unet.parameters())
                    ema_model.copy_to(unet.parameters())

                run_validation(unet, noise_scheduler, validation_batch, epoch, args, accelerator, weight_dtype)

                if args.use_ema:
                    ema_model.restore(unet.parameters())

            if epoch % args.save_model_epochs == 0 or epoch == args.num_epochs - 1:
                unet = accelerator.unwrap_model(model)

                if args.use_ema:
                    ema_model.store(unet.parameters())
                    ema_model.copy_to(unet.parameters())

                save_conditional_components(unet, noise_scheduler, args.output_dir)

                if args.use_ema:
                    ema_model.restore(unet.parameters())

                if args.push_to_hub:
                    upload_folder(
                        repo_id=repo_id,
                        folder_path=args.output_dir,
                        commit_message=f"Epoch {epoch}",
                        ignore_patterns=["step_*", "epoch_*"],
                    )

    accelerator.end_training()


if __name__ == "__main__":
    args = parse_args()
    main(args)
